// eslint-disable-next-line no-unused-vars
const services = [
  {
    layers: 'osm_waterways',
    format: 'image/png',
    transparent: true,
    maxZoom: 20,
    minZoom: 1,
    displayName: 'Waterways',
    type: 'vector',
    group: 'Basemap'
  },
  {
    layers: 'osm_roads',
    format: 'image/png',
    transparent: true,
    maxZoom: 20,
    minZoom: 1,
    displayName: 'Roads',
    type: 'vector',
    group: 'Basemap'
  },
  {
    layers: 'osm_buildings',
    format: 'image/png',
    transparent: true,
    maxZoom: 20,
    minZoom: 1,
    displayName: 'Buildings',
    type: 'vector',
    group: 'Basemap'
  },
  {
    layers: 'basemap_bbox',
    format: 'image/png',
    transparent: true,
    maxZoom: 20,
    minZoom: 1,
    displayName: 'Basemap boundary',
    type: 'vector',
    group: 'Basemap'
  },
  {
    layers: 'selection',
    format: 'image/png',
    transparent: true,
    maxZoom: 20,
    minZoom: 1,
    displayName: 'Current selection',
    type: 'vector',
    group: 'Basemap'
  },
  {
    layers: 'time_map_from_points',
    format: 'image/png',
    transparent: true,
    maxZoom: 20,
    minZoom: 3,
    displayName: 'Start point',
    type: 'vector',
    group: 'Time map'
  },
  {
    layers: 'time_map_via_points',
    format: 'image/png',
    transparent: true,
    maxZoom: 20,
    minZoom: 3,
    displayName: 'Via point',
    type: 'vector',
    group: 'Time map'
  },
  {
    layers: 'time_map_stricken_area',
    format: 'image/png',
    transparent: true,
    maxZoom: 20,
    minZoom: 3,
    displayName: 'Affected area',
    type: 'vector',
    group: 'Time map'
  },
  {
    layers: 'time_map_result',
    format: 'image/png',
    transparent: true,
    legend: true,
    maxZoom: 20,
    minZoom: 1,
    displayName: 'Road-level time map',
    type: 'vector',
    group: 'Time map'
  },
  {
    layers: 'ltca_dem',
    format: 'image/png',
    transparent: true,
    legend: true,
    maxZoom: 20,
    minZoom: 3,
    displayName: 'Elevation map',
    type: 'raster',
    group: 'Latacunga thematic maps'
  },
  {
    layers: 'ltca_admin',
    format: 'image/png',
    transparent: true,
    legend: true,
    maxZoom: 20,
    minZoom: 3,
    displayName: 'Administrative units',
    type: 'vector',
    group: 'Latacunga thematic maps'
  },
  {
    layers: 'ltga_densidad_poblacion',
    format: 'image/png',
    transparent: true,
    legend: true,
    maxZoom: 20,
    minZoom: 3,
    displayName: 'Population density',
    type: 'vector',
    group: 'Latacunga thematic maps'
  },
  {
    layers: 'ltga_interpolated_density',
    format: 'image/png',
    transparent: true,
    legend: true,
    maxZoom: 20,
    minZoom: 3,
    displayName: 'Population density raster',
    type: 'raster',
    group: 'Latacunga thematic maps'
  },
  {
    layers: 'ltca_greenhouses',
    format: 'image/png',
    transparent: true,
    legend: true,
    maxZoom: 20,
    minZoom: 3,
    displayName: 'Greenhouses',
    type: 'vector',
    group: 'Latacunga thematic maps'
  },
  {
    layers: 'ltca_farms',
    format: 'image/png',
    transparent: true,
    legend: true,
    maxZoom: 20,
    minZoom: 3,
    displayName: 'Farms and orchards',
    type: 'vector',
    group: 'Latacunga thematic maps'
  },
  {
    layers: 'ltca_schools',
    format: 'image/png',
    transparent: true,
    legend: true,
    maxZoom: 20,
    minZoom: 3,
    displayName: 'Schools',
    type: 'vector',
    group: 'Latacunga thematic maps'
  },
  {
    layers: 'ltca_doct_offices',
    format: 'image/png',
    transparent: true,
    legend: true,
    maxZoom: 20,
    minZoom: 3,
    displayName: 'Doctors and dentists',
    type: 'vector',
    group: 'Latacunga thematic maps'
  },
  {
    layers: 'ltca_hospitals',
    format: 'image/png',
    transparent: true,
    legend: true,
    maxZoom: 20,
    minZoom: 3,
    displayName: 'Hospitals and clinics',
    type: 'vector',
    group: 'Latacunga thematic maps'
  },
  {
    layers: 'ltga_buildingfloors',
    format: 'image/png',
    transparent: true,
    legend: true,
    maxZoom: 20,
    minZoom: 3,
    displayName: 'Building floors',
    type: 'vector',
    group: 'Latacunga thematic maps'
  },
  {
    layers: 'ltga_eje_vial',
    format: 'image/png',
    transparent: true,
    legend: true,
    maxZoom: 20,
    minZoom: 3,
    displayName: 'Latacunga roads',
    type: 'vector',
    group: 'Latacunga thematic maps'
  },
  {
    layers: 'ltga_vias_2004',
    format: 'image/png',
    transparent: true,
    legend: true,
    maxZoom: 20,
    minZoom: 3,
    displayName: 'Cotopaxi roads',
    type: 'vector',
    group: 'Latacunga thematic maps'
  },
  {
    layers: 'ltga_luminaria',
    format: 'image/png',
    transparent: true,
    legend: true,
    maxZoom: 20,
    minZoom: 3,
    displayName: 'Lighting',
    type: 'vector',
    group: 'Latacunga thematic maps'
  },
  {
    layers: 'tramodistriaereo',
    format: 'image/png',
    transparent: true,
    legend: true,
    maxZoom: 20,
    minZoom: 3,
    displayName: 'Air distribution section',
    type: 'vector',
    group: 'Latacunga thematic maps'
  },
  {
    layers: 'tramodistrisub',
    format: 'image/png',
    transparent: true,
    legend: true,
    maxZoom: 20,
    minZoom: 3,
    displayName: 'Underground distribution section',
    type: 'vector',
    group: 'Latacunga thematic maps'
  },
  {
    layers: 'ltga_cultivo_principal',
    format: 'image/png',
    transparent: true,
    legend: true,
    maxZoom: 20,
    minZoom: 3,
    displayName: 'Agriculture main crops',
    type: 'vector',
    group: 'Latacunga thematic maps'
  },
  {
    layers: 'ltga_uso_cobertura',
    format: 'image/png',
    transparent: true,
    legend: true,
    maxZoom: 20,
    minZoom: 3,
    displayName: 'Land use and land cover',
    type: 'vector',
    group: 'Latacunga thematic maps'
  },
  {
    layers: 'ltca_productive_infrastructure',
    format: 'image/png',
    transparent: true,
    legend: true,
    maxZoom: 20,
    minZoom: 3,
    displayName: 'Productive infrastructure',
    type: 'vector',
    group: 'Latacunga thematic maps'
  },
  {
    layers: 'ltca_producer_associations',
    format: 'image/png',
    transparent: true,
    legend: true,
    maxZoom: 20,
    minZoom: 3,
    displayName: 'Producer associations',
    type: 'vector',
    group: 'Latacunga thematic maps'
  },
  {
    layers: 'ltca_markets_squares',
    format: 'image/png',
    transparent: true,
    legend: true,
    maxZoom: 20,
    minZoom: 3,
    displayName: 'Markets and squares',
    type: 'vector',
    group: 'Latacunga thematic maps'
  },
  {
    layers: 'ltca_safe_points',
    format: 'image/png',
    transparent: true,
    legend: true,
    maxZoom: 20,
    minZoom: 3,
    displayName: 'Safe points',
    type: 'vector',
    group: 'Latacunga thematic maps'
  },
  {
    layers: 'ltca_evacuation_routes',
    format: 'image/png',
    transparent: true,
    legend: true,
    maxZoom: 20,
    minZoom: 3,
    displayName: 'Evacuation routes',
    type: 'vector',
    group: 'Latacunga thematic maps'
  },
  {
    layers: 'ltca_sirens',
    format: 'image/png',
    transparent: true,
    legend: true,
    maxZoom: 20,
    minZoom: 3,
    displayName: 'Early warning sirens',
    type: 'vector',
    group: 'Latacunga thematic maps'
  },
  {
    layers: 'ltga_amenaza_coto',
    format: 'image/png',
    transparent: true,
    legend: true,
    maxZoom: 20,
    minZoom: 3,
    displayName: 'Affected areas',
    type: 'vector',
    group: 'Latacunga volcanic threats'
  },
  {
    layers: 'ltga_grado_amenaza',
    format: 'image/png',
    transparent: true,
    legend: true,
    maxZoom: 20,
    minZoom: 3,
    displayName: 'Volcano lahar flow',
    type: 'vector',
    group: 'Latacunga volcanic threats'
  },
  {
    layers: 'ltga_isopacas',
    format: 'image/png',
    transparent: true,
    legend: true,
    maxZoom: 20,
    minZoom: 3,
    displayName: 'Cotopaxi ash fall',
    type: 'vector',
    group: 'Latacunga volcanic threats'
  },
  {
    layers: 'ltga_vulnerabilidad',
    format: 'image/png',
    transparent: true,
    legend: true,
    maxZoom: 20,
    minZoom: 3,
    displayName: 'Vulnerability',
    type: 'vector',
    group: 'Latacunga volcanic threats'
  }
]
